//! Wei-exact port of `CvammCurve.sol` (EverlongLabs blockend), the closed-form
//! reservation curve the CvammALM venue trades on. Normalized inventory (x volatile,
//! y stable) sits on the level set of `y^2 + (x+c)y - k/x = 0` with `c = 1/(2A) - 1`
//! and `4k = 1/(2A)`; the venue holds a band of it ([`Support`]) scaled by `kappa`
//! and located by an anchor sqrt price. Validated against the fixture grid in
//! `testdata/cvamm_fixtures.csv` (generated by a forge script running the
//! via_ir-pinned library) and against fills settled by the deployed Berachain venue.
//!
//! Every symbol is the WAD-scaled integer of the same name, every division floors
//! and sqrt is floor-sqrt, exactly as on-chain. Two properties are load-bearing at
//! the wei scale and must survive any edit:
//! - [`y_at_x`] computes the radicand as ONE sum before the square root. Two independently floored
//!   terms move in opposite directions in x, so their sum can step UP as x increases — a
//!   non-monotone y, which the stable-in bisection brackets on.
//! - `c` is negative for every valid A (A > WAD/2), so `b = x + c` is carried as a magnitude plus
//!   sign to avoid the catastrophic cancellation of the naive form.

use alloy::primitives::{I256, U256, U512};
use serde::{Deserialize, Serialize};

use crate::evm::protocol::safe_math::sqrt_u256;

/// Brackets the stable-in bisection around the x<->y symmetry seed (~140x the worst
/// seed error over the domain).
const SEED_WINDOW: u64 = 1 << 16;

pub fn wad() -> U256 {
    U256::from(10u128.pow(18))
}

fn wad_squared() -> U256 {
    U256::from(10u128.pow(36))
}

fn q96() -> U256 {
    U256::from(1u8) << 96
}

fn min_x_wad() -> U256 {
    U256::from(10u64.pow(15))
}

fn max_x_wad() -> U256 {
    U256::from(1_999u64 * 10u64.pow(15))
}

fn min_a_wad() -> U256 {
    U256::from(5u64 * 10u64.pow(17) + 1)
}

fn max_a_wad() -> U256 {
    U256::from(10u128.pow(21))
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CvammMathError {
    /// Coordinate outside `[MIN_X_WAD, MAX_X_WAD]`.
    Domain,
    /// Amplification outside `[MIN_A_WAD, MAX_A_WAD]`.
    Amplification,
    /// The span does not carve a valid band out of the curve domain.
    Span,
    /// Anchor or kappa is zero — the book was retracted, nothing is quotable.
    RetractedBook,
    /// A `mulDiv` quotient exceeded 256 bits (cannot happen for in-domain inputs).
    Overflow,
}

/// The funded band: domain slice `[x_lo, x_hi]` of the curve at amplification
/// `a_wad`, with `y_hi = y(x_hi)` cached so held inventory is a subtraction.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Support {
    pub a_wad: U256,
    pub x_lo: U256,
    pub x_hi: U256,
    pub y_hi: U256,
}

/// An exact-input fill in token units: the gross output before the fee haircut, the
/// coordinate after the fill, and any input the finite band left unspent.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Fill {
    pub gross_out: U256,
    pub x_after: U256,
    pub unspent_in: U256,
}

fn narrow(wide: U512) -> Result<U256, CvammMathError> {
    let limbs = wide.as_limbs();
    if limbs[4..].iter().any(|limb| *limb != 0) {
        return Err(CvammMathError::Overflow);
    }
    Ok(U256::from_limbs([limbs[0], limbs[1], limbs[2], limbs[3]]))
}

pub fn mul_div_down(a: U256, b: U256, denominator: U256) -> Result<U256, CvammMathError> {
    if denominator.is_zero() {
        return Err(CvammMathError::Overflow);
    }
    let wide = U512::from(a) * U512::from(b);
    narrow(wide / U512::from(denominator))
}

fn mul_div_up(a: U256, b: U256, denominator: U256) -> Result<U256, CvammMathError> {
    if denominator.is_zero() {
        return Err(CvammMathError::Overflow);
    }
    let wide = U512::from(a) * U512::from(b);
    let (quotient, remainder) = (wide / U512::from(denominator), wide % U512::from(denominator));
    let rounded = if remainder.is_zero() { quotient } else { quotient + U512::from(1u8) };
    narrow(rounded)
}

/// `4k = 1/(2A)` and `|c| = WAD - 4k` (c is negative for every valid A).
fn four_k_and_neg_c(a_wad: U256) -> Result<(U256, U256), CvammMathError> {
    if a_wad < min_a_wad() || a_wad > max_a_wad() {
        return Err(CvammMathError::Amplification);
    }
    let four_k = wad_squared() / (a_wad << 1);
    Ok((four_k, wad() - four_k))
}

/// The curve: stable inventory `y` at volatile coordinate `x`, the positive root of
/// `y^2 + (x+c)y - k/x = 0` as `(root -/+ |b|)/2` branching on sign(b).
pub fn y_at_x(x_wad: U256, a_wad: U256) -> Result<U256, CvammMathError> {
    if x_wad < min_x_wad() || x_wad > max_x_wad() {
        return Err(CvammMathError::Domain);
    }
    let (four_k, neg_c) = four_k_and_neg_c(a_wad)?;

    let b_negative = x_wad < neg_c;
    let abs_b = if b_negative { neg_c - x_wad } else { x_wad - neg_c };

    // ONE floor in the radicand: abs_b^2 is exact (<= 4e36), the k-term floors once.
    let radicand = abs_b * abs_b + mul_div_down(four_k, wad_squared(), x_wad)?;
    let root = sqrt_u256(radicand).map_err(|_| CvammMathError::Overflow)?;

    let y = if b_negative { root + abs_b } else { root - abs_b };
    Ok(y >> 1)
}

/// Marginal price at `x`, normalized so the anchor (`x = WAD/2`) is exactly WAD.
/// `p = -dy/dx = y*(2x + y + c) / (x*(x + 2y + c))`, decreasing in `x`.
pub fn price_at_x(x_wad: U256, a_wad: U256) -> Result<U256, CvammMathError> {
    let y_wad = y_at_x(x_wad, a_wad)?;
    let (four_k, _) = four_k_and_neg_c(a_wad)?;
    let c = i256(four_k)? - i256(wad())?;
    let x = i256(x_wad)?;
    let y = i256(y_wad)?;
    let two = I256::try_from(2u8).expect("2 fits I256");
    let numerator = y * (two * x + y + c);
    let denominator = x * (x + two * y + c);
    if numerator <= I256::ZERO || denominator <= I256::ZERO {
        return Err(CvammMathError::Domain);
    }
    mul_div_down(numerator.into_raw(), wad(), denominator.into_raw())
}

/// Inverse of [`price_at_x`]: 128-halving bisection, clamping at the domain edges.
/// Accurate to a few wei on the LOW side (worst 251 wei at A = 1000e18), exactly as
/// on-chain — this bias is part of the shipped semantics.
pub fn x_at_price(target_price_wad: U256, a_wad: U256) -> Result<U256, CvammMathError> {
    let mut lo = min_x_wad();
    let mut hi = max_x_wad();
    if target_price_wad >= price_at_x(lo, a_wad)? {
        return Ok(lo);
    }
    if target_price_wad <= price_at_x(hi, a_wad)? {
        return Ok(hi);
    }
    for _ in 0..128 {
        let mid = (lo + hi) >> 1;
        if mid == lo {
            break;
        }
        if price_at_x(mid, a_wad)? > target_price_wad {
            lo = mid;
        } else {
            hi = mid;
        }
    }
    Ok((lo + hi) >> 1)
}

/// Build the funded band from a price span, mirroring `CvammCurve.supportFor`:
/// `span_up_wad` is the highest normalized price held, `span_dn_wad` the reciprocal
/// of the lowest. Spans the curve cannot express are rejected, not clamped.
pub fn support_for(
    a_wad: U256,
    span_up_wad: U256,
    span_dn_wad: U256,
) -> Result<Support, CvammMathError> {
    if span_up_wad <= wad() || span_dn_wad <= wad() {
        return Err(CvammMathError::Span);
    }
    let x_lo = x_at_price(span_up_wad, a_wad)?;
    let x_hi = x_at_price(mul_div_down(wad(), wad(), span_dn_wad)?, a_wad)?;
    if x_lo <= min_x_wad() || x_hi >= max_x_wad() || x_lo >= x_hi {
        return Err(CvammMathError::Span);
    }
    Ok(Support { a_wad, x_lo, x_hi, y_hi: y_at_x(x_hi, a_wad)? })
}

/// Exact-input fill in normalized units. Volatile-in (price falls, x rises) is
/// closed form; stable-in inverts y -> x with the contract's seeded bisection.
/// Returns `(amount_out, x_after, input_unused)`; unused input is non-zero only
/// where the funded band truncates the fill.
fn norm_swap_exact_in(
    support: &Support,
    x_wad: U256,
    volatile_in: bool,
    amount_in_wad: U256,
) -> Result<(U256, U256, U256), CvammMathError> {
    // A no-input fill MUST be a no-op: the stable-in bisection lands on the LEFTMOST
    // coordinate of a floored-y tread, so without this guard a zero input would move
    // the coordinate.
    if amount_in_wad.is_zero() {
        return Ok((U256::ZERO, x_wad, U256::ZERO));
    }
    let y = y_at_x(x_wad, support.a_wad)?;

    if volatile_in {
        let room = if support.x_hi > x_wad { support.x_hi - x_wad } else { U256::ZERO };
        let used = amount_in_wad.min(room);
        let unused = amount_in_wad - used;
        let x_after = x_wad + used;
        let y_after = y_at_x(x_after, support.a_wad)?;
        let out = if y > y_after { y - y_after } else { U256::ZERO };
        return Ok((out, x_after, unused));
    }
    stable_in_fill(support, x_wad, y, amount_in_wad)
}

/// Paying the stable leg raises y and lowers x; inverting y -> x needs a bisection,
/// seeded off the invariant's x <-> y symmetry.
fn stable_in_fill(
    support: &Support,
    x_wad: U256,
    y: U256,
    amount_in_wad: U256,
) -> Result<(U256, U256, U256), CvammMathError> {
    let y_max = y_at_x(support.x_lo, support.a_wad)?;
    let reachable = if y_max > y { y_max - y } else { U256::ZERO };
    let used = amount_in_wad.min(reachable);
    if used.is_zero() {
        return Ok((U256::ZERO, x_wad, amount_in_wad));
    }
    let unused = amount_in_wad - used;

    let y_target = y + used;
    let (mut lo, mut hi) = seed_bracket(support.x_lo, x_wad, support, y_target)?;
    for _ in 0..128 {
        let mid = (lo + hi) >> 1;
        if mid == lo {
            break;
        }
        if y_at_x(mid, support.a_wad)? > y_target {
            lo = mid;
        } else {
            hi = mid;
        }
    }
    let x_after = hi;
    let out = if x_wad > x_after { x_wad - x_after } else { U256::ZERO };
    Ok((out, x_after, unused))
}

/// Narrow `[lo, hi]` around `y_at_x(y_target)` — valid because the level set is
/// symmetric under swapping the coordinates — and adopt the window ONLY if it
/// brackets the root under the same predicate the bisection uses.
fn seed_bracket(
    lo: U256,
    hi: U256,
    support: &Support,
    y_target: U256,
) -> Result<(U256, U256), CvammMathError> {
    if y_target < min_x_wad() || y_target > max_x_wad() {
        return Ok((lo, hi));
    }
    let seed = y_at_x(y_target, support.a_wad)?;
    let window = U256::from(SEED_WINDOW);
    let lo_seed = if seed > lo + window { seed - window } else { lo };
    let hi_seed = (seed + window).min(hi);
    if lo_seed >= hi_seed {
        return Ok((lo, hi));
    }
    if y_at_x(lo_seed, support.a_wad)? <= y_target {
        return Ok((lo, hi));
    }
    if y_at_x(hi_seed, support.a_wad)? > y_target {
        return Ok((lo, hi));
    }
    Ok((lo_seed, hi_seed))
}

/// Token amount -> normalized inventory, FLOORING — two mulDivs in this exact
/// order, one factor of the anchor sqrt per leg.
fn to_normalized(
    amount: U256,
    anchor_sqrt_x96: U256,
    kappa: U256,
    stable: bool,
) -> Result<U256, CvammMathError> {
    let t = mul_div_down(amount, wad(), kappa)?;
    if stable {
        mul_div_down(t, q96(), anchor_sqrt_x96)
    } else {
        mul_div_down(t, anchor_sqrt_x96, q96())
    }
}

/// Normalized inventory -> token amount, FLOORING (protocol-favourable).
pub fn to_token(
    norm: U256,
    anchor_sqrt_x96: U256,
    kappa: U256,
    stable: bool,
) -> Result<U256, CvammMathError> {
    let t = mul_div_down(kappa, norm, wad())?;
    if stable {
        mul_div_down(t, anchor_sqrt_x96, q96())
    } else {
        mul_div_down(t, q96(), anchor_sqrt_x96)
    }
}

/// [`to_token`], CEILING — used only to price a truncated fill's charge.
fn to_token_ceil(
    norm: U256,
    anchor_sqrt_x96: U256,
    kappa: U256,
    stable: bool,
) -> Result<U256, CvammMathError> {
    let t = mul_div_up(kappa, norm, wad())?;
    if stable {
        mul_div_up(t, anchor_sqrt_x96, q96())
    } else {
        mul_div_up(t, q96(), anchor_sqrt_x96)
    }
}

/// The exact-input fill in TOKEN units, mirroring `CvammCurve.swapExactInX96`.
/// `gross_out` is the output BEFORE the fee haircut. An input below normalized
/// resolution (~kappa/WAD in the leg's own units) is reported entirely unspent; a
/// fill truncated by the band rounds its charge UP and caps at `amount_in`.
pub fn swap_exact_in_x96(
    support: &Support,
    anchor_sqrt_x96: U256,
    kappa: U256,
    x_wad: U256,
    stable_in: bool,
    amount_in: U256,
) -> Result<Fill, CvammMathError> {
    if anchor_sqrt_x96.is_zero() || kappa.is_zero() {
        return Err(CvammMathError::RetractedBook);
    }
    let in_norm = to_normalized(amount_in, anchor_sqrt_x96, kappa, stable_in)?;
    if in_norm.is_zero() {
        return Ok(Fill { gross_out: U256::ZERO, x_after: x_wad, unspent_in: amount_in });
    }
    // The curve's flag is VOLATILE-in; this one is STABLE-in — opposites, as are
    // the legs.
    let (out_norm, x_after, unused_norm) = norm_swap_exact_in(support, x_wad, !stable_in, in_norm)?;
    let gross_out = to_token(out_norm, anchor_sqrt_x96, kappa, !stable_in)?;
    if unused_norm.is_zero() {
        return Ok(Fill { gross_out, x_after, unspent_in: U256::ZERO });
    }
    let used_norm = in_norm - unused_norm;
    let used_tokens = to_token_ceil(used_norm, anchor_sqrt_x96, kappa, stable_in)?;
    let unspent_in = if amount_in > used_tokens { amount_in - used_tokens } else { U256::ZERO };
    Ok(Fill { gross_out, x_after, unspent_in })
}

fn i256(value: U256) -> Result<I256, CvammMathError> {
    I256::try_from(value).map_err(|_| CvammMathError::Overflow)
}
